### ISSUE TITLE
can  not setup persistent storage

### ISSUE THREAD

**Issue by silent-mobius** [kusnier/vagrant-persistent-storage#103]
hi,
I am using fedora31 and manjaro, with kernel 4.19 on both of them. On virtualization, i am using virutalbox 6.0.10, and vagrant 2.2.4 with your plugin version of 0.0.47.
i configured the file as follows: 
```bash 
config.vm.define "raid" do |raid|
    raid.vm.box="centos/7"
    raid.vm.hostname="ansible"
    raid.vm.network "private_network", ip: "10.0.180.100"
    raid.vm.persistent_storage.enabled = true
    raid.vm.persistent_storage.location = "./sdd.vdi"
    raid.vm.persistent_storage.size = 1024
    raid.vm.persistent_storage.mountname = 'sdbl'
    raid.vm.persistent_storage.filesystem = 'ext4'
    raid.vm.persistent_storage.mountpoint = '/mnt/'
    raid.vm.persistent_storage.volgroupname = 'myvolgroup'
```
and i am getting this :
==> raid: Using /home/que/Projects/IaC/Raid for persistent storage.
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The following settings shouldn't exist: persistent_storage
mind giving a hand ? am i missiing something ?

**Comment by paul-gene** [comment]
It should be `raid.persistent_storage.enabled = true` etc

However, I tried provisioning a new VM with this plugin, using the instructions, and whilst the storage was created, it didn't seem to get used for mysql

**Comment by silent-mobius** [comment]
after seeking a long hours, it turns out, i configuring it incorrectly... found it on documentation page.
