### ISSUE TITLE
the existing persistent storage is reformated for non-LVM setting.

### ISSUE THREAD

**Issue by dictcp** [kusnier/vagrant-persistent-storage#30]
Persistent storage is reformated for non-LVM partition after vagrant destroy and up, as no identifier is added for non-LVM partition

**Comment by dictcp** [comment]
pull request for the fix
https://github.com/kusnier/vagrant-persistent-storage/pull/31

**Comment by kusnier** [comment]
Pull request was merged and a new release is out. Thanks.
