### ISSUE TITLE
Stderr: VBoxManage: error: Could not find a controller named 'SATA Controller'

### ISSUE THREAD

**Issue by ksingh7** [kusnier/vagrant-persistent-storage#33]
I have installed this plugin , but still i am facing the same issue. 
Environment:

Host machine : OSX
Vagrant Version : Latest Version: 1.7.2
Vagrant Box image : hansode/centos-6.5-x86_64

$ vagrant plugin list
vagrant-persistent-storage (0.0.15)
vagrant-share (1.1.3, system)
$

==> osd0: Running 'pre-boot' VM customizations...
A customization command failed:

["storageattach", :id, "--storagectl", "SATA Controller", "--port", 0, "--device", 0, "--type", "hdd", "--medium", "disk-0-0.vdi"]

The following error was experienced:
# <Vagrant::Errors::VBoxManageError: There was an error while executing VBoxManage, a CLI used by Vagrant

for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "2613dc11-8637-419e-8b2f-e40d1973dbe2", "--storagectl", "SATA Controller", "--port", "0", "--device", "0", "--type", "hdd", "--medium", "disk-0-0.vdi"]

Stderr: VBoxManage: error: Could not find a controller named 'SATA Controller'

Please fix this customization and try again.
$

**Comment by ksingh7** [comment]
So managed to find  the solution. 

Error Message :  "Stderr: VBoxManage: error: Could not find a controller named 'SATA Controller'"

Solution : The vagrant image that you are using does NOT have a SATA Controller, that's why its throwing this error. You can check your vagrant box if it really hav3 SATA Controller.

Now if your vagrant box that you have downloaded from https://atlas.hashicorp.com/ does not have SATA Controller by default . Then you need to create your own virtualbox machine , add a SATA Controller to it and repackage it as a vagrant BOX and use it. 

What i have observed is none of the CentOS box images hosted on https://atlas.hashicorp.com/ have default SATA Controller attached to them. ( i might be wrong , i have tried 4-5 images ) and finally builded my own box.

Sample Output : 

CentOS Vagrant box , that does not have SATA Controller

$ cat /Users/ksingh/.vagrant.d/boxes/TyrCeph/0/virtualbox/box.ovf | grep -i storagecontroller
      <StorageControllers>
        <StorageController name="IDE Controller" type="PIIX4" PortCount="2" useHostIOCache="true" Bootable="true">
        </StorageController>
      </StorageControllers>
$

Vagrant Precise box that have a SATA Controller

$ cat /Users/ksingh/.vagrant.d/boxes/hashicorp-VAGRANTSLASH-precise64/1.1.0/virtualbox/box.ovf | grep -i storagecontroller
      <StorageControllers>
        <StorageController name="IDE Controller" type="PIIX4" PortCount="2" useHostIOCache="true" Bootable="true">
        </StorageController>
        <StorageController name="SATA Controller" type="AHCI" PortCount="1" useHostIOCache="false" Bootable="true" IDE0MasterEmulationPort="0" IDE0SlaveEmulationPort="1" IDE1MasterEmulationPort="2" IDE1SlaveEmulationPort="3">
        </StorageController>
      </StorageControllers>
$

**Comment by kusnier** [comment]
Right now I have not time. I'll watch it later.

**Comment by kbroughton** [comment]
For me, The issue was resolved by changing "SATA Controller" to "SATAController".

I noticed looking at the virtualbox gui for adding disks that there was no space for the default disk.

["storageattach", :id, "--storagectl", "SATAController", "--port", 0, "--device", 0, "--type", "hdd", "--medium", "disk-0-0.vdi"]

**Comment by kooyeed** [comment]
For me, The issue was resolved by changing "SATA Controller" to "SATA".

thanks.

**Comment by istr** [comment]
You might want to fix this along the lines of:

https://gist.github.com/leifg/4713995#gistcomment-1615625

Just create a separate controller for each hdd attached.
That way the plugin could (some day) support more than one additional VDI, e.g.
```sh
/mnt/psql
/mnt/backup
/mnt/redis
```

**Comment by kusnier** [comment]
Can you test this with the latest version of the plugin?

**Comment by kusnier** [comment]
Maybe fixed with last release. 0.0.22

**Comment by aisrael** [comment]
When using box `"ubuntu/xenial64"`, then the controller name should be `'SCSI'`. You can list the available storage controllers using `VBoxManage showvminfo [vmname]`.

**Comment by zminds** [comment]
.customize ["storageattach", :id, "--storagectl", "IDE", "--port", "1", '--device', "1", "--type", "hdd", "--medium", "diskname.vdi"]

you can try ide controller

**Comment by diboanches** [comment]
Yea, there is enough to think about 

I also noticed that no need to use "storagectl" cuz it has already exists. 
My code to add new storage is: 

`file_to_disk ='/path/to/disk.vdi'

Vagrant.configure(2) do |config|
  config.vm.define "iscsitarget" do |iscsitarget|
    iscsitarget.vm.box = "ubuntu/trusty64"
    iscsitarget.vm.provider "virtualbox" do |vb|
      vb.name = "VM NAME"
      unless File.exist?(file_to_disk)
        vb.customize ['createhd', '--filename', file_to_disk, '--variant', 'Fixed', '--size', 1 * 1024]
      end
      vb.memory = "1024"
      vb.customize ['storageattach', "VM TEST",  '--storagectl', 'SATAController', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
    end
  end
end`

It is working fine right now

**Comment by tklo** [comment]
In Ubuntu Xenial the controller is called "SCSI". 💩

**Comment by alimeerutech** [comment]
```
VBoxManage list vms -l | grep -i storage
```

to find the name of your storage driver

**Comment by OmSaran** [comment]
I think VirtualBox images have SATA drivers. Adding `--provider=virtualbox` helped resolve the issue for me. I am guessing that when I explicitly specify the provider, it downloads a different image than when not specified.

**Comment by nulluuid** [comment]
I had the same problem and just went to GUI and realize that I have to specify "SATA" instead of "SATA controller" 

```
            node.vm.provider :virtualbox do |vb|
                vb.memory = "1024"
                vb.cpus = 1
                vb.customize [
                    "storageattach", :id,
                    "--storagectl", "SATA",
                    "--port", "1",
                    "--type", "dvddrive",
                    "--medium", "nocloud.iso"
                ]
            end
```
