### ISSUE TITLE
0.0.18 is broken with hotplug errors

### ISSUE THREAD

**Issue by justicel** [kusnier/vagrant-persistent-storage#44]
I get the following error now:

=> pcobox: ** Attaching persistent storage **
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "87e69694-8e0d-4474-bd06-472b6473b7c4", "--storagectl", "IDE Controller", "--port", "1", "--device", "0", "--type", "hdd", "--medium", "data/.pco-box_perm.vdi", "--hotpluggable", "on"]

Stderr: VBoxManage: error: Controller 'IDE Controller' does not support changing the hot-pluggable device flag
VBoxManage: error: Details: code VBOX_E_NOT_SUPPORTED (0x80bb0009), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "SetHotPluggableForDevice(Bstr(pszCtl).raw(), port, device, TRUE)" at line 881 of file VBoxManageStorageController.cpp

My config is as follows:

  config.persistent_storage.enabled      = true
  config.persistent_storage.location     = "data/.pco-box_perm.vdi"
  config.persistent_storage.size         = 20000
  config.persistent_storage.mountname    = 'persistvol'
  config.persistent_storage.filesystem   = 'ext4'
  config.persistent_storage.mountpoint   = '/opt/persist'
  config.persistent_storage.volgroupname = 'persist'
  config.persistent_storage.mountoptions = ['defaults', 'relatime']

**Comment by justicel** [comment]
So the primary controller is IDE, which I don't believe indeed does support hotplugging. I'm assuming that for devices like this the 'patch' that was added in 0.0.18 will need to be bypassed to resolve.

**Comment by kusnier** [comment]
Thanks for the hint. Released 0.0.19 with a fix.

**Comment by paultyng** [comment]
:+1: fixes my issue locally
