### ISSUE TITLE
Create VDI With Initial Size

### ISSUE THREAD

**Issue by opticyclic** [kusnier/vagrant-persistent-storage#53]
I know on `vagrant up` that my attached vdi is going to grow immediately to 20GB due to the import of a database dump.

Rather than have the vdi start small then keep dynamically increasing, is it possible to set the initial vdi size?

**Comment by craigmaloney** [comment]
It seems the latest version has the following option:

`config.persistent_storage.variant    = 'Fixed'`

That seemed to work for me.

**Comment by chucknelson** [comment]
@kusnier - This issue doesn't seem to be relevant or valid anymore, since this feature is supported. Can the issue be closed?

**Comment by kusnier** [comment]
Thanks! close
