### ISSUE TITLE
How to add two disks?

### ISSUE THREAD

**Issue by acesuares** [kusnier/vagrant-persistent-storage#61]
How to add two disks?

**Comment by macbeth76** [comment]
I also would like to have two disks, is this possible?

**Comment by vmichnowicz** [comment]
It does not look like adding multiple disks is currently supported. I think this would be a nice feature though.

**Comment by sporniket** [comment]
This issues seems duplicate of #22 and should be closed

**Comment by kusnier** [comment]
Duplicate Close #61
See #22
