### ISSUE TITLE
Typo: volgroupname => part_type_code

### ISSUE THREAD

**Issue by robnagler** [kusnier/vagrant-persistent-storage#78]
I think [config.rb, line 124](https://github.com/kusnier/vagrant-persistent-storage/blob/be94ee0d38104240b1682e00450957712a2fb189/lib/vagrant-persistent-storage/config.rb#L124) has a typo. Should be:

```ruby
             :is_class   => part_type_code.class.to_s,
```

**Comment by kusnier** [comment]
Fixed. Thank you.
0.0.35 was released.
