### ISSUE TITLE
warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by bitboxer** [kusnier/vagrant-persistent-storage#81]
After updating to the latest vagrant / virtualbox I got this message:

```
.vagrant.d/gems/2.4.2/gems/vagrant-persistent-storage-0.0.35/lib/vagrant-persistent-storage/config.rb:85: warning: constant ::Fixnum is deprecated
```

Looks like vagrant updated the ruby it ships and this might need to be fixed 👍 . Thank you for reading this.

**Comment by cpierce** [comment]
same issue
