### ISSUE TITLE
Injected script not created properly, and disk not mounted

### ISSUE THREAD

**Issue by verdurin** [kusnier/vagrant-persistent-storage#90]
With `0.0.41` I was seeing that owing to faulty option parsing logic, the script injected into the VM was missing the code to mount the partition.

By properly segregating the `format` and `mount` checks, this problem is fixed and an existing disk (i.e. already formatted) is mounted.

See #89

**Comment by kusnier** [comment]
Fixed with 0.0.42
Thank you!
