### ISSUE TITLE
Compatibility with VirtualBox 6.0

### ISSUE THREAD

**Issue by Okeanos** [kusnier/vagrant-persistent-storage#93]
With VirtualBox 6.0 having been released on [December 18th 2018](https://www.virtualbox.org/wiki/News) I am wondering whether there are any (short term) plans to make the plugin compatible with it?

There are at least two lines of code (https://github.com/kusnier/vagrant-persistent-storage/blob/5f066920a665653638ba19dd0f700cd3118b1494/lib/vagrant-persistent-storage/providers/virtualbox/driver/base.rb#L13 and https://github.com/kusnier/vagrant-persistent-storage/blob/5f066920a665653638ba19dd0f700cd3118b1494/lib/vagrant-persistent-storage/providers/virtualbox/driver/base.rb#L15) that need to be adapted as far as I can see.

I manually changed these to work for 6.0 locally for now but official support would be nice.
- the same `portcount` parameter as used for 4.3 and 5.x is necessary
- the `portcount` value has to be (?!) `16` – at least in my case it throws an error if it isn't

I have not used the plugin to create a disk from scratch yet with VBox 6.0 only after an upgrade and re-attaching an existing storage.

**Comment by kusnier** [comment]
Thank you for the information. Can you also check if this is working from scratch with a new vm?
I have updated my VirtualBox and vagrant. When I run the ./test.sh command from this repository i get valid checks. Maybe this occurs only when the previous storage was created with an earlier version of VirtualBox.

**Comment by Okeanos** [comment]
Okay, I am no longer certain what happened but apparently changing the `portcount` value is not necessary at all. Guess something else was interfering — I tested a box from scratch and the migrated one just now and it works as long as the parameter name is correct.

**Comment by csuka** [comment]
Does it work with Virtualbox 6?
If so, can you update the README as well, thanks.

**Comment by kusnier** [comment]
I have updated the readme. Thanks.
