### ISSUE TITLE
/tmp/ cannot execute.

### ISSUE THREAD

**Issue by csuka** [kusnier/vagrant-persistent-storage#96]
I can't execute on /tmp/, thus this whole package fails.
Can you change the location of where the script is being launched from, such as /home/vagrant/

**Comment by kusnier** [comment]
Can you explain what I have exactly to do to reproduce the problem? Some information about your host system would also be helpful. Thank you.

**Comment by csuka** [comment]
Using CentOS 7. I've got a system which is mounted as `ro` on /tmp. 
I'd like to use this plugin, but since the system I"m using cannot execute on /tmp/ this plugin doesn't work.

You default your script to /tmp/disk_operations_<name>.sh. 
But the .sh cannot execute since my /tmp/ is mounted as read-only. My company has done this due to security reasons....

So perhaps, you can create a variable of where the disk_operations scripts are set. Instead of the default /tmp/ folder

**Comment by kusnier** [comment]
Can you check if the following command will provide a writeable temporary dir?
When this works i could update the script to determinate the temporary folder dynamically.

```sh
dirname $(mktemp -u)
```

**Comment by kusnier** [comment]
I have updated the script now the temp dir is calculated through mktemp.
Tomorrow I will make some tests and provide a new version.

**Comment by kusnier** [comment]
I have release v0.0.45 which uses now mktemp to calculate the temporary directory.
Now it should work.
Thank you.
